name: Feature Request
description: Suggest a change or addition to the theme
labels: feature request
body:
  - type: input
    attributes:
      label: Summary
      description: A short summary of your request
    validations:
      required: true
  - type: dropdown
    attributes:
      multiple: true
      label: Related Component
      options:
        - UI Theme
        - Editor Theme
        - Key Maps
        - Code Style
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: >
        What would you like to change or add?
        Why would this improvement be useful?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshot / Example
      description: If applicable, include a screenshot or reference showing the desired look or behavior.
  - type: textarea
    attributes:
      label: Additional Context
      description: Any other relevant information.